"""
EVRYWR.MEDIA — Configuración Marzo 2026
Edita este archivo para personalizar el calendario del mes.
"""

MES = "MARZO 2026"

SEMANAS = {
    "W1": "POSITIONING",
    "W2": "AUTHORITY",
    "W3": "HUMANIZATION",
    "W4": "CONVERSION",
}

# Subfolders within CLIENTES (leave empty if no active clients yet)
CLIENTES = []

POSTS = [
    # ── W1 · POSITIONING ──────────────────────────────────────────────────────
    {
        "fecha_key": "MAR03",
        "fecha": "MAR 3",
        "dia": "Lunes",
        "semana": "W1",
        "tipo": "EDU",
        "plataforma": "Instagram",
        "formato": "Carousel",
        "titulo_corto": "5 Errores Algoritmo",
        "titulo": "5 errores que matan el alcance en Instagram 2026",
        "hook": "Tu contenido es bueno pero nadie lo ve. El problema no eres tú, es tu estrategia de 2024...",
        "script": "Hooks + screenshots de métricas. ManyChat keyword: AUDIT",
        "notas": "",
        "hashtags": "#instagram #estrategia #socialmedia",
    },
    {
        "fecha_key": "MAR05",
        "fecha": "MAR 5",
        "dia": "Miércoles",
        "semana": "W1",
        "tipo": "CASE",
        "plataforma": "Instagram",
        "formato": "Reel",
        "titulo_corto": "Cliente Placeholder 1",
        "titulo": "[PLACEHOLDER] Trabajo/Testimonio Cliente — De 200 views a 15K en 30 días",
        "hook": "De 200 views a 15K en 30 días — cómo lo hicimos para [Cliente]",
        "script": "⚠ REQUIERE CLIENTE REAL. Usar métrica real + antes/después. ManyChat: CASO",
        "notas": "",
        "hashtags": "#casodeexito #resultados",
    },
    {
        "fecha_key": "MAR07",
        "fecha": "MAR 7",
        "dia": "Viernes",
        "semana": "W1",
        "tipo": "BTS",
        "plataforma": "Instagram",
        "formato": "Story→Reel",
        "titulo_corto": "Reel con IA Higgsfield",
        "titulo": "Así creamos un Reel con IA en 15 minutos (Higgsfield)",
        "hook": "La gente piensa que la IA reemplaza creativos. Falso. La IA potencia a los que tienen ideas...",
        "script": "Pantalla compartida, proceso real sin filtros",
        "notas": "",
        "hashtags": "#ia #reels #bts",
    },
    # ── W2 · AUTHORITY ────────────────────────────────────────────────────────
    {
        "fecha_key": "MAR10",
        "fecha": "MAR 10",
        "dia": "Lunes",
        "semana": "W2",
        "tipo": "EDU",
        "plataforma": "Instagram",
        "formato": "Carousel",
        "titulo_corto": "Hashtags 2026",
        "titulo": "Hashtags en 2026: por qué ya NO funcionan (y qué hacer)",
        "hook": "Llevás usando 30 hashtags y tu alcance sigue igual. Es hora de hablar de SEO...",
        "script": "Data de investigación 2026",
        "notas": "",
        "hashtags": "#hashtags #seo #instagram2026",
    },
    {
        "fecha_key": "MAR12",
        "fecha": "MAR 12",
        "dia": "Miércoles",
        "semana": "W2",
        "tipo": "TREND",
        "plataforma": "Instagram",
        "formato": "Reel",
        "titulo_corto": "Instagram SEO",
        "titulo": "Instagram ahora es un buscador — y nadie lo está usando bien",
        "hook": "Google indexa tus posts. Si no optimizás para SEO, eres invisible...",
        "script": "Screen recording de búsqueda Google mostrando posts",
        "notas": "",
        "hashtags": "#instagramseo #marketing",
    },
    {
        "fecha_key": "MAR14",
        "fecha": "MAR 14",
        "dia": "Viernes",
        "semana": "W2",
        "tipo": "COMM",
        "plataforma": "Instagram",
        "formato": "Post+Stories",
        "titulo_corto": "Encuesta Redes",
        "titulo": "Pregunta: ¿Qué les cuesta MÁS de manejar sus redes?",
        "hook": "¿Qué los está frenando? ¿Tiempo? ¿Ideas? ¿Edición?",
        "script": "Encuesta interactiva — guardar respuestas para contenido futuro",
        "notas": "",
        "hashtags": "#comunidad #engagement",
    },
    # ── W3 · HUMANIZATION ─────────────────────────────────────────────────────
    {
        "fecha_key": "MAR17",
        "fecha": "MAR 17",
        "dia": "Lunes",
        "semana": "W3",
        "tipo": "EDU",
        "plataforma": "Instagram",
        "formato": "Reel",
        "titulo_corto": "Carousels vs Reels",
        "titulo": "Carousels vs Reels: cuál usar según tu número de seguidores",
        "hook": "Si tenés menos de 50K, hacé Reels. Si tenés más, carousels. Aquí la data...",
        "script": "Gráfica animada con data real",
        "notas": "",
        "hashtags": "#reels #carousel #estrategia",
    },
    {
        "fecha_key": "MAR19",
        "fecha": "MAR 19",
        "dia": "Miércoles",
        "semana": "W3",
        "tipo": "CASE",
        "plataforma": "Instagram",
        "formato": "Carousel",
        "titulo_corto": "Cliente Placeholder 2",
        "titulo": "[PLACEHOLDER] Proyecto: [Nombre Cliente] — Objetivo / Proceso / Resultados",
        "hook": "Proyecto: [Nombre Cliente] — Objetivo / Proceso / Resultados",
        "script": "⚠ REQUIERE CLIENTE REAL. Mostrar entregables reales. ManyChat: CASO",
        "notas": "",
        "hashtags": "#proyecto #agencia",
    },
    {
        "fecha_key": "MAR21",
        "fecha": "MAR 21",
        "dia": "Viernes",
        "semana": "W3",
        "tipo": "BTS",
        "plataforma": "Instagram",
        "formato": "Reel",
        "titulo_corto": "Un Dia en EVRYWR",
        "titulo": "Un día en EVRYWR: de brief a post publicado",
        "hook": "7 AM: llega el brief. 6 PM: está en el feed del cliente. Así pasa la magia...",
        "script": "Time-lapse del equipo trabajando",
        "notas": "",
        "hashtags": "#bts #agencia #equipo",
    },
    # ── W4 · CONVERSION ───────────────────────────────────────────────────────
    {
        "fecha_key": "MAR24",
        "fecha": "MAR 24",
        "dia": "Lunes",
        "semana": "W4",
        "tipo": "EDU",
        "plataforma": "Instagram",
        "formato": "Carousel",
        "titulo_corto": "Hooks 10 Templates",
        "titulo": "Cómo escribir hooks que paran el scroll (10 templates)",
        "hook": "El 80% del alcance se decide en los primeros 3 segundos. Roba estos 10 hooks...",
        "script": "Templates copiables en slides. ManyChat: HOOKS",
        "notas": "",
        "hashtags": "#copywriting #hooks #contenido",
    },
    {
        "fecha_key": "MAR26",
        "fecha": "MAR 26",
        "dia": "Miércoles",
        "semana": "W4",
        "tipo": "CASE",
        "plataforma": "Instagram",
        "formato": "Reel",
        "titulo_corto": "Cliente Placeholder 3",
        "titulo": "[PLACEHOLDER] Cliente: [Nombre] — Desafío / Estrategia / ROI",
        "hook": "Cliente: [Nombre] — Desafío / Estrategia / ROI",
        "script": "⚠ REQUIERE CLIENTE REAL. Testimonial en video o quote gráfico. ManyChat: CASO",
        "notas": "",
        "hashtags": "#roi #resultados #casodeexito",
    },
    {
        "fecha_key": "MAR28",
        "fecha": "MAR 28",
        "dia": "Viernes",
        "semana": "W4",
        "tipo": "TREND",
        "plataforma": "Instagram",
        "formato": "Post+Carousel",
        "titulo_corto": "Agencias IA",
        "titulo": "Por qué las agencias que usan IA sin estrategia están quebrando",
        "hook": "La IA no es una varita mágica. Es una herramienta. Sin cerebro humano, es basura...",
        "script": "Opinión bold — posicionamiento de expertise",
        "notas": "",
        "hashtags": "#ia #agencias #estrategia",
    },
    {
        "fecha_key": "MAR31",
        "fecha": "MAR 31",
        "dia": "Lunes",
        "semana": "W4",
        "tipo": "COMM",
        "plataforma": "Instagram",
        "formato": "Reel+Stories",
        "titulo_corto": "Recap Marzo",
        "titulo": "Recap Marzo: lo que funcionó, lo que aprendimos, lo que viene",
        "hook": "Cerramos el mes con [X] posts, [X] alcance. Esto aprendimos...",
        "script": "Transparencia total — Build in Public",
        "notas": "",
        "hashtags": "#recap #buildinpublic #marzo",
    },
]
